FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["DataModelMigrator/DataModelMigrator.csproj", "DataModelMigrator/"]
COPY ["DataLayer/DataLayer.csproj", "DataLayer/"]
RUN dotnet restore "DataModelMigrator/DataModelMigrator.csproj"
COPY . .
WORKDIR "/src/DataModelMigrator"
RUN dotnet build "DataModelMigrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DataModelMigrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DataModelMigrator.dll"]